### ISSUE TITLE
Current World Edit is Terrible

### ISSUE THREAD

**Issue by TheDoverKing** [ThroneCraft/public#128] opened 2021-01-03 20:25 UTC
**Describe the bug**

The current world edit plugin is far worse than any previous one we used. This one is so slow that it's borderline unusable in my opinion. //copy takes a ridiculous period of time to copy even simple things and the same goes for then pasting it. Brushes seem to work depending on how they feel at any given time. In general this world edit version is horrible and I can't stand using it to the point it is faster doing things by hand most of the time now.

**Screenshots**

https://imgur.com/qM7XZj9

**Additional context**

Please can we go back to one of the previous versions/plugins of world edit.

***Minecraft username:***

TheDoverKing

**Comment by jvdoorn** [comment] 2021-01-04 13:04
Duplicate of #127.

**Closed by jvdoorn** 2021-01-04 13:04 UTC
Labels: bug, duplicate
